depends_on:
  - test

when:
  - event: [tag, pull_request]
  - event: push
    branch: ${CI_DEFAULT_BRANCH}

variables:
  - &buildx-plugin 'woodpeckerci/plugin-docker-buildx:5.0.0'
  - &repo 'woodpeckerci/plugin-prettier'
  - &platforms 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le'

steps:
  dryrun:
    image: *buildx-plugin
    settings:
      dry_run: true
      repo: *repo
      username: woodpeckerbot
      platforms: *platforms
      tag: test
    when:
      event: pull_request

  publish-next:
    image: *buildx-plugin
    settings:
      repo: *repo
      username: woodpeckerbot
      platforms: *platforms
      tag: next
      password:
        from_secret: docker_password
    when:
      branch: main
      event: push

  publish-tag:
    image: *buildx-plugin
    settings:
      repo: *repo
      username: woodpeckerbot
      platforms: *platforms
      tag: [latest, '${CI_COMMIT_TAG}']
      password:
        from_secret: docker_password
    when:
      event: tag
